-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- TABLE: borrower_account
-- Populated once per borrower during CA processing. Never updated.
-- ============================================================
CREATE TABLE IF NOT EXISTS borrower_account (
    borrower_account  INTEGER       PRIMARY KEY,
    borrower_name     VARCHAR(255)  NOT NULL,
    country           VARCHAR(100)  NOT NULL,
    email             VARCHAR(255),
    borrower_type     VARCHAR(100),  -- Corporate, Financial Institution, Government, Other
    risk_meter        VARCHAR(20)   NOT NULL CHECK (risk_meter IN ('Low', 'Medium', 'High')),
    kyc_status        BOOLEAN       NOT NULL DEFAULT FALSE,
    kyc_valid_till    DATE,
    fcc_flag          BOOLEAN       NOT NULL DEFAULT FALSE
);

-- ============================================================
-- TABLE: firm_balance
-- Composite PK: (firm_account, currency)
-- Must exist before loan_info since loan_info references firm_account.
-- ============================================================
CREATE TABLE IF NOT EXISTS firm_balance (
    firm_account  INTEGER       NOT NULL,
    currency      VARCHAR(10)   NOT NULL,
    balance       FLOAT         NOT NULL DEFAULT 0.0,
    PRIMARY KEY (firm_account, currency)
);

-- ============================================================
-- TABLE: loan_info
-- One row per deal. deal_id auto-generated by system.
-- ============================================================
CREATE TABLE IF NOT EXISTS loan_info (
    deal_id            SERIAL        PRIMARY KEY,
    deal_name          VARCHAR(255)  NOT NULL UNIQUE,
    committed_amount   FLOAT         NOT NULL,
    funded             FLOAT         NOT NULL DEFAULT 0.0,
    margin             FLOAT,
    interest_rate      FLOAT         NOT NULL,
    interest_rate_type VARCHAR(20)   NOT NULL CHECK (interest_rate_type IN ('Fixed', 'Floating')),
    origination_date   DATE          NOT NULL,
    maturity_date      DATE          NOT NULL,
    status             VARCHAR(20)   NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Closed')),
    fees_applicable    BOOLEAN       NOT NULL DEFAULT FALSE,
    currency           VARCHAR(10)   NOT NULL,
    ca_pdf_url         VARCHAR(1024),
    borrower_account   INTEGER       NOT NULL REFERENCES borrower_account(borrower_account),
    firm_account       INTEGER       NOT NULL
    -- firm_account references firm_balance(firm_account) — not a FK constraint because
    -- firm_balance uses composite PK; currency is required to uniquely identify the row.
);

-- ============================================================
-- TABLE: transaction_log
-- Append-only audit log. Never updated after insert.
-- hil_triggers and hil_decisions are JSONB arrays.
-- ============================================================
CREATE TABLE IF NOT EXISTS transaction_log (
    transaction_id         SERIAL        PRIMARY KEY,
    deal_id                INTEGER       NOT NULL REFERENCES loan_info(deal_id),
    notice_type            VARCHAR(50)   NOT NULL,
    notice_pdf_url         VARCHAR(1024),
    amount                 FLOAT         NOT NULL,
    currency               VARCHAR(10)   NOT NULL,
    notice_date            DATE          NOT NULL,
    processed_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    agent_decision         VARCHAR(100),
    human_in_loop_triggered BOOLEAN      NOT NULL DEFAULT FALSE,
    hil_triggers           JSONB         NOT NULL DEFAULT '[]'::jsonb,
    hil_decisions          JSONB         NOT NULL DEFAULT '[]'::jsonb,
    final_outcome          VARCHAR(20)   NOT NULL CHECK (final_outcome IN ('Success', 'Failed', 'Halted')),
    failure_reason         TEXT
);

-- ============================================================
-- TABLE: ca_embeddings  (pgvector store)
-- Structural chunks of CA documents with embeddings.
-- tsvector column for full-text search (hybrid retrieval).
-- text-embedding-3-small = 1536 dimensions
-- ============================================================
CREATE TABLE IF NOT EXISTS ca_embeddings (
    chunk_id      SERIAL        PRIMARY KEY,
    deal_id       INTEGER       NOT NULL REFERENCES loan_info(deal_id),
    section_name  VARCHAR(255),
    clause_number VARCHAR(100),
    chunk_text    TEXT          NOT NULL,
    embedding     vector(1536),
    chunk_tsv     TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', chunk_text)) STORED
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Loan info lookups by deal name (fuzzy match pre-filter)
CREATE INDEX IF NOT EXISTS idx_loan_info_deal_name ON loan_info(deal_name);
CREATE INDEX IF NOT EXISTS idx_loan_info_status    ON loan_info(status);
CREATE INDEX IF NOT EXISTS idx_loan_info_borrower  ON loan_info(borrower_account);

-- Transaction log lookups
CREATE INDEX IF NOT EXISTS idx_txlog_deal_id     ON transaction_log(deal_id);
CREATE INDEX IF NOT EXISTS idx_txlog_notice_type ON transaction_log(notice_type);
CREATE INDEX IF NOT EXISTS idx_txlog_notice_date ON transaction_log(notice_date);

-- pgvector cosine similarity index (IVFFlat — good for free Neon tier)
CREATE INDEX IF NOT EXISTS idx_ca_embeddings_vector
    ON ca_embeddings USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 50);

-- Full-text search index on embeddings
CREATE INDEX IF NOT EXISTS idx_ca_embeddings_tsv ON ca_embeddings USING GIN (chunk_tsv);

-- Filter by deal_id in hybrid retrieval
CREATE INDEX IF NOT EXISTS idx_ca_embeddings_deal_id ON ca_embeddings(deal_id);
